"""add is checked in user

Revision ID: 070ce330e242
Revises: cd15297ae862
Create Date: 2025-05-19 17:07:37.085581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '070ce330e242'
down_revision: Union[str, None] = 'cd15297ae862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_checked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'is_checked', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('M', 'F', 'O', name='genders'),
               type_=postgresql.ENUM('M', 'F', 'O', name='gender'),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'is_checked')
    # ### end Alembic commands ###
