"""add is checked in user

Revision ID: 1a97ddb793f2
Revises: 070ce330e242
Create Date: 2025-05-19 17:32:15.711298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a97ddb793f2'
down_revision: Union[str, None] = '070ce330e242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isChecked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
   

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('M', 'F', 'O', name='genders'),
               type_=postgresql.ENUM('M', 'F', 'O', name='gender'),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'isChecked')
    # ### end Alembic commands ###
