"""add dob and gender in user

Revision ID: cd15297ae862
Revises: 4445d7e7ff0b
Create Date: 2025-05-19 16:22:02.625364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd15297ae862'
down_revision: Union[str, None] = '4445d7e7ff0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gender_enum = sa.Enum('M', 'F', 'O', name='gender')

def upgrade():
    # Create enum type in the DB
    gender_enum.create(op.get_bind(), checkfirst=True)

    # If gender column already exists and needs conversion
    op.execute("ALTER TABLE users ALTER COLUMN gender TYPE gender USING gender::gender")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('M', 'F', 'O', name='genders'),
               type_=postgresql.ENUM('M', 'F', 'O', name='gender'),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
